- hosts: all
  tasks:
    - name: create service template
       become: true 
       template:
         src: example.service.j2
         dest: /etc/systemd/system/example1.service
  
    - name: copy artifact
       copy:
         src: example1
         dest: /home/vagrant/example1
   
    - name: enable and start service
      become: true
      systemd:
         name: example1
         enable: yes
         state: restarted
